apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: aimee-typescript-reactjs
  name: aimee-typescript-reactjs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: aimee-typescript-reactjs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: aimee-typescript-reactjs
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: aimeelynnramirez3/aimee-typescript-reactjs
        imagePullPolicy: Always
        name: aimee-typescript-reactjs
        ports:
        - containerPort: 3000
        resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: 
       - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory
status: {}
