version: '3.4'
services:
          
  aimee-typescript-reactjs:
    image: aimeelynnramirez3/aimee-typescript-reactjs
    build: .
    environment:
     #- GET_HOSTS_FROM=dns
     NODE_ENV: production
    ports:
      - "3000"
  #   labels:
  #      kompose.service.type: LoadBalancer  
       
  # redis-master:
  #     image: k8s.gcr.io/redis:e2e
  #     ports:
  #       - "6379"

  #   redis-slave:
  #     image: gcr.io/google_samples/gb-redisslave:v3
  #     ports:
  #       - "6379"
  #     environment:
  #       - GET_HOSTS_FROM=dns

  #   frontend:
  #     image: gcr.io/google-samples/gb-frontend:v4
  #     ports:
  #       - "80:80"
  #     environment:
  #       - GET_HOSTS_FROM=dns
  #     labels:
  #       kompose.service.type: LoadBalancer